---
latitude: 40.76446
longitude: -73.98082
name: Wellington Hotel
email: victor@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 871 Seventh Ave
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10019'
_hotel_id: WEL028
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
